### ISSUE TITLE
Obsługa plików - lokalizacja

### ISSUE THREAD

**Issue by slawmalcz** [slawmalcz/C-C-UPD-Communication#11]
Problem obsługi plików dotyczący lokalizacja. Gdzie powinny zapisywać się przesłane pliki.
a) Do ścliśle ustalonej przez aplikacje lokalizacji
b) Serwer podaje lokalizacje do zapisu
c) Po stronie klienckiej ustawiana jako opcja
d) Przy każdorazowym przesłaniu pliku pytamy o lokalizacje docelową
e) inne...

**Comment by animx11** [comment]
W tym przypadku bym zrobił to opcją a), ewentualnie c). Sądzę, że przy tych opcjach będzie najmniej roboty i ciężko będzie sprawić żeby coś się wykrzaczyło.
